import { PixelSprite } from './PixelSprite';

// Color palette
const COLORS = {
  TRANSPARENT: 'transparent',
  BROWN: '#8B4513',
  DARK_GREEN: '#006400',
  LIGHT_GREEN: '#90EE90',
  GREY: '#808080',
  DARK_GREY: '#404040',
  BLUE: '#0000FF',
  LIGHT_BLUE: '#ADD8E6',
  YELLOW: '#FFFF00',
};

// Tree sprite
export const tree = new PixelSprite([
  [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.DARK_GREEN, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
  [COLORS.TRANSPARENT, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.TRANSPARENT],
  [COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.DARK_GREEN],
  [COLORS.TRANSPARENT, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.DARK_GREEN, COLORS.TRANSPARENT],
  [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.BROWN, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
  [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.BROWN, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
  [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.BROWN, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
]);

// Rock sprite
export const rock = new PixelSprite([
  [COLORS.TRANSPARENT, COLORS.GREY, COLORS.GREY, COLORS.TRANSPARENT],
  [COLORS.GREY, COLORS.GREY, COLORS.GREY, COLORS.GREY],
  [COLORS.GREY, COLORS.DARK_GREY, COLORS.GREY, COLORS.GREY],
  [COLORS.TRANSPARENT, COLORS.GREY, COLORS.GREY, COLORS.TRANSPARENT],
]);

// House sprite
export const house = new PixelSprite([
  [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
  [COLORS.TRANSPARENT, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.TRANSPARENT],
  [COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED, COLORS.RED],
  [COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN],
  [COLORS.BROWN, COLORS.BROWN, COLORS.YELLOW, COLORS.BROWN, COLORS.YELLOW, COLORS.BROWN, COLORS.BROWN],
  [COLORS.BROWN, COLORS.BROWN, COLORS.YELLOW, COLORS.BROWN, COLORS.YELLOW, COLORS.BROWN, COLORS.BROWN],
  [COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN, COLORS.BROWN],
]);

// Water tile sprite
export const water = new PixelSprite([
  [COLORS.BLUE, COLORS.BLUE, COLORS.LIGHT_BLUE, COLORS.BLUE],
  [COLORS.LIGHT_BLUE, COLORS.BLUE, COLORS.BLUE, COLORS.BLUE],
  [COLORS.BLUE, COLORS.BLUE, COLORS.LIGHT_BLUE, COLORS.BLUE],
  [COLORS.BLUE, COLORS.LIGHT_BLUE, COLORS.BLUE, COLORS.BLUE],
]);

// Grass tile sprite
export const grass = new PixelSprite([
  [COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN],
  [COLORS.LIGHT_GREEN, COLORS.DARK_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN],
  [COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.DARK_GREEN],
  [COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN, COLORS.LIGHT_GREEN],
]);
