/**
 * PlayerSprite.js - Creates Sierra-style player character sprites
 */

import { PixelSprite } from './PixelSprite.js';
import { COLORS } from '../common/color-palette.js';

// Create Sierra-style player sprites (front, back, left, right)
export const createPlayerSprites = () => {
    // Front-facing player sprite in Sierra style
    const playerFront = new PixelSprite([
        [COLORS.TRANSPARENT, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.TRANSPARENT],
        [COLORS.HAIR_BROWN, COLORS.SKIN_TONE, COLORS.SKIN_TONE, COLORS.HAIR_BROWN],
        [COLORS.TRANSPARENT, COLORS.SKIN_TONE, COLORS.SKIN_TONE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE],
        [COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.PANTS_NAVY, COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.PANTS_NAVY]
    ]);
    
    // Left-facing sprite
    const playerLeft = new PixelSprite([
        [COLORS.TRANSPARENT, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SKIN_TONE, COLORS.SKIN_TONE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.TRANSPARENT, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.TRANSPARENT, COLORS.TRANSPARENT]
    ]);
    
    // Right-facing sprite
    const playerRight = new PixelSprite([
        [COLORS.TRANSPARENT, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SKIN_TONE, COLORS.SKIN_TONE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.TRANSPARENT]
    ]);
    
    // Back-facing sprite
    const playerBack = new PixelSprite([
        [COLORS.TRANSPARENT, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.TRANSPARENT],
        [COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN, COLORS.HAIR_BROWN],
        [COLORS.TRANSPARENT, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.TRANSPARENT],
        [COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE],
        [COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE, COLORS.SHIRT_BLUE],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.TRANSPARENT, COLORS.PANTS_NAVY, COLORS.PANTS_NAVY, COLORS.TRANSPARENT],
        [COLORS.PANTS_NAVY, COLORS.TRANSPARENT, COLORS.TRANSPARENT, COLORS.PANTS_NAVY]
    ]);
    
    return {
        playerFront,
        playerLeft,
        playerRight,
        playerBack
    };
};

export default createPlayerSprites;